apiVersion: apps/v1
kind: Deployment
metadata:
  name: "@app.name@"
spec:
  selector:
    matchLabels:
      app: "@app.name@"
  template:
    metadata:
      labels:
        app: "@app.name@"
    spec:
      containers:
        - name: "@app.name@"
          image: "gcr.io/@project.name@/jib-image"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "@app.name@"
spec:
  selector:
    app: "@app.name@"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080